FROM ghcr.io/puppeteer/puppeteer:latest
WORKDIR /app
COPY backend/package*.json backend/tsconfig.json ./backend/
RUN cd backend && npm install
COPY backend ./backend
WORKDIR /app/backend
RUN npm run build
EXPOSE 4000
ENV PORT=4000
CMD ["node", "dist/server.js"]
