import ADHeroStatus from "@/components/ad-dashboard/ADHeroStatus";
import DCHealthPanel from "@/components/ad-dashboard/DCHealthPanel";
import ReplicationHealth from "@/components/ad-dashboard/ReplicationHealth";
import SecurityMonitoring from "@/components/ad-dashboard/SecurityMonitoring";
import PrivilegeChanges from "@/components/ad-dashboard/PrivilegeChanges";
import ADRiskScore from "@/components/ad-dashboard/ADRiskScore";

const ActiveDirectory = () => (
  <div className="min-h-screen bg-background">
    <div className="max-w-[1280px] mx-auto px-6 py-5 space-y-5">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="bg-navy rounded-lg p-2">
            <svg className="h-5 w-5 text-primary-foreground" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2" />
              <circle cx="9" cy="7" r="4" />
              <path d="M23 21v-2a4 4 0 0 0-3-3.87" />
              <path d="M16 3.13a4 4 0 0 1 0 7.75" />
            </svg>
          </div>
          <div>
            <h1 className="text-xl font-bold text-foreground tracking-tight">Active Directory Monitoring</h1>
            <p className="text-xs text-muted-foreground">Enterprise Directory Services Dashboard</p>
          </div>
        </div>
        <p className="text-xs text-muted-foreground">
          Report generated: {new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}{" "}
          {new Date().toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" })}
        </p>
      </div>

      <ADHeroStatus />
      <DCHealthPanel />
      <ReplicationHealth />
      <SecurityMonitoring />

      <div className="grid grid-cols-3 gap-3">
        <div className="col-span-2">
          <PrivilegeChanges />
        </div>
        <ADRiskScore />
      </div>

      <footer className="text-center py-3 border-t border-border">
        <p className="text-xs text-muted-foreground">Generated by ICT Active Directory Monitoring System</p>
      </footer>
    </div>
  </div>
);

export default ActiveDirectory;
