import HeroStatus from "@/components/dashboard/HeroStatus";
import JobSummaryCards from "@/components/dashboard/JobSummaryCards";
import CriticalVMTable from "@/components/dashboard/CriticalVMTable";
import StorageUsage from "@/components/dashboard/StorageUsage";
import RestoreReadiness from "@/components/dashboard/RestoreReadiness";
import RiskScore from "@/components/dashboard/RiskScore";

const Index = () => (
  <div className="min-h-screen bg-background">
    <div className="max-w-[1280px] mx-auto px-6 py-5 space-y-5">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="bg-navy rounded-lg p-2">
            <svg className="h-5 w-5 text-primary-foreground" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
            </svg>
          </div>
          <div>
            <h1 className="text-xl font-bold text-foreground tracking-tight">Veeam Backup Monitoring</h1>
            <p className="text-xs text-muted-foreground">Enterprise Infrastructure Protection Dashboard</p>
          </div>
        </div>
        <p className="text-xs text-muted-foreground">
          Report generated: {new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}{" "}
          {new Date().toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" })}
        </p>
      </div>

      {/* 1. Hero Status */}
      <HeroStatus />

      {/* 2. Job Summary */}
      <JobSummaryCards />

      {/* 3. Critical VM Table */}
      <CriticalVMTable />

      {/* 4. Storage + 5. Restore + 6. Risk Score */}
      <StorageUsage />

      <div className="grid grid-cols-3 gap-3">
        <div className="col-span-2">
          <RestoreReadiness />
        </div>
        <RiskScore />
      </div>

      {/* Footer */}
      <footer className="text-center py-3 border-t border-border">
        <p className="text-xs text-muted-foreground">Generated by ICT Backup Monitoring System</p>
      </footer>
    </div>
  </div>
);

export default Index;
